# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0579838c932adf657d21ce8aebc358176b60ff97bc8a2395de09ae41e02efbbe5fc3404d8a328a856fe8f09883ef2c38f66e8e4cf53b1dbbc2ec0ff5b5f92e0

test:
  secret_key_base: dc47cc718211219c23ec91e5a6e765942132df655be4da9a364a6a90d7024847646b1793c74b29280bba20dfb07007c079abc24cd420c00bcc078c42043b102d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
